### ISSUE TITLE
Issue with projection matrix in landscape

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#13]
- i noticed the objects are a bit squezzed vertically when using the phone in landscape.
- in portrait, the perspective appears correct tho.

my guess : it is around the projection matrix.

**Comment by judax** [comment]
IMO what's happening is that the matrix is assuming that the camera is "really" being rendered fullscreen when the size of the canvas is not (the webview only takes the space on the screen below the URL navigation bar). In landscape it might be more noticeable because the percentage of the URL navigation bar corresponding to the overall screen height is much bigger than in portrait. I might try to compensate the navigation bar ans see what happens.

**Comment by patricknelson** [comment]
This may no longer be an issue @jeromeetienne, can you check again? I'm not noticing this when using THREE.js.
